spring:
  datasource:
    url: jdbc:sqlserver://huseyin-sqlserver.database.windows.net:1433;database=huseyindb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: toor
    password: 12345Aa*
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191